name: Food experience
analytics: {}
github: true
description: all about having fun and good food
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content: []
layout_spectrum: 0.9686452648602426
color:
  lightness: 0.3240378573536873
  brandColors:
    - '#6C6E58'
    - '#3E423A'
    - '#417378'
    - '#A4CFBE'
    - '#F4F7D9'
  saturation: 0.4384072523098439
  brandStrength: 0.2752747933845967
  rhythmicContrast: 0.4459888683632016
content_rating:
  adult: false
typography_spectrum: 0.8432624572888017
opengraph: {}
title: '#foodie'
